<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9vSkicM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9vSkicM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9vSkicM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9vSkicM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9vSkicM\App_KernelDevDebugContainer([
    'container.build_hash' => '9vSkicM',
    'container.build_id' => '1ba28790',
    'container.build_time' => 1660466154,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9vSkicM');
