<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJilke9M\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJilke9M/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJilke9M.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJilke9M\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJilke9M\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jilke9M',
    'container.build_id' => '6ea62de5',
    'container.build_time' => 1660495625,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJilke9M');
